//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_NEW.Source
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_com_config_printer_group_mapping
    {
        public System.Guid group_printer_id { get; set; }
        public System.Guid group_id { get; set; }
        public System.Guid printer_id { get; set; }
        public int sequence { get; set; }
        public string bartender_exe_filepath { get; set; }
        public string bartender_btw_filepath { get; set; }
        public string bartender_argument_command { get; set; }
        public string bartender_data_filepath { get; set; }
        public string bartender_trigger_filepath { get; set; }
        public string is_active { get; set; }
        public System.DateTime create_date { get; set; }
        public string create_by { get; set; }
    
        public virtual t_com_config_printer t_com_config_printer { get; set; }
        public virtual t_com_config_printer_group t_com_config_printer_group { get; set; }
    }
}
