//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_NEW.Source
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_com_config_printer_group
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public t_com_config_printer_group()
        {
            this.t_com_config_printer_group_mapping = new HashSet<t_com_config_printer_group_mapping>();
        }
    
        public System.Guid group_id { get; set; }
        public string group_name { get; set; }
        public string group_desc { get; set; }
        public string group_type { get; set; }
        public Nullable<System.Guid> wh_master_id { get; set; }
        public string location_id { get; set; }
        public string is_active { get; set; }
        public System.DateTime create_date { get; set; }
        public string create_by { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_com_config_printer_group_mapping> t_com_config_printer_group_mapping { get; set; }
        public virtual t_wms_wh t_wms_wh { get; set; }
    }
}
