//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_NEW.Source
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_host_wms_receipt_conf_detail_export
    {
        public string receipt_detail_id { get; set; }
        public string receipt_id { get; set; }
        public string processing_code { get; set; }
        public string processing_status { get; set; }
        public string wh_id { get; set; }
        public string owner_id { get; set; }
        public string inbound_order_number { get; set; }
        public string line_number { get; set; }
        public string item_number { get; set; }
        public string location { get; set; }
        public string parent_lpn { get; set; }
        public string lpn { get; set; }
        public string lot_number { get; set; }
        public string expiry_date { get; set; }
        public string serial_number { get; set; }
        public string uom { get; set; }
        public Nullable<double> qty_received { get; set; }
        public string receipt_item_status { get; set; }
        public Nullable<System.DateTime> receipt_date { get; set; }
        public Nullable<System.DateTime> mfg_date { get; set; }
        public string user_def1 { get; set; }
        public string user_def2 { get; set; }
        public string user_def3 { get; set; }
        public string user_def4 { get; set; }
        public string user_def5 { get; set; }
        public string user_def6 { get; set; }
        public Nullable<double> user_def7 { get; set; }
        public Nullable<double> user_def8 { get; set; }
        public Nullable<System.DateTime> user_def9 { get; set; }
        public Nullable<System.DateTime> user_def10 { get; set; }
        public string attribute1 { get; set; }
        public string attribute2 { get; set; }
        public string attribute3 { get; set; }
        public string attribute4 { get; set; }
        public string attribute5 { get; set; }
        public string create_by { get; set; }
        public System.DateTime create_date { get; set; }
        public byte[] rowversion { get; set; }
        public Nullable<double> qty_Damaged { get; set; }
        public Nullable<System.DateTime> interface_date { get; set; }
        public string erp_production_line { get; set; }
        public Nullable<System.DateTime> print_date { get; set; }
        public Nullable<System.DateTime> posting_date { get; set; }
    
        public virtual t_host_wms_receipt_conf_header_export t_host_wms_receipt_conf_header_export { get; set; }
    }
}
