//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_NEW.Source
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_host_wms_outbound_order
    {
        public System.Guid outbound_order_id { get; set; }
        public string host_record_id { get; set; }
        public string record_type { get; set; }
        public string processing_code { get; set; }
        public string processing_status { get; set; }
        public string wh_id { get; set; }
        public string owner_id { get; set; }
        public string order_number { get; set; }
        public string type { get; set; }
        public string order_status { get; set; }
        public string customer_order_number { get; set; }
        public string customer_code { get; set; }
        public string customer_purchase_order { get; set; }
        public System.DateTime order_create_date { get; set; }
        public Nullable<System.DateTime> order_ship_date { get; set; }
        public string department { get; set; }
        public string load_id { get; set; }
        public Nullable<int> load_sequence_number { get; set; }
        public string tracking_number { get; set; }
        public string rush_order { get; set; }
        public string back_order_flag { get; set; }
        public string ship_to_code { get; set; }
        public string ship_to_name { get; set; }
        public string ship_to_address_line_1 { get; set; }
        public string ship_to_address_line_2 { get; set; }
        public string ship_to_address_line_3 { get; set; }
        public string ship_to_city { get; set; }
        public string ship_to_province { get; set; }
        public string ship_to_postal_code { get; set; }
        public string ship_to_country { get; set; }
        public string ship_to_country_name { get; set; }
        public string ship_to_contact_name { get; set; }
        public string ship_to_phone_number { get; set; }
        public string bill_to_code { get; set; }
        public string bill_to_name { get; set; }
        public string bill_to_address_line_1 { get; set; }
        public string bill_to_address_line_2 { get; set; }
        public string bill_to_address_line_3 { get; set; }
        public string bill_to_city { get; set; }
        public string bill_to_province { get; set; }
        public string bill_to_postal_code { get; set; }
        public string bill_to_country { get; set; }
        public string bill_to_country_name { get; set; }
        public string bill_to_contact_name { get; set; }
        public string bill_to_phone_number { get; set; }
        public string requested_by { get; set; }
        public string user_def1 { get; set; }
        public string user_def2 { get; set; }
        public string user_def3 { get; set; }
        public string user_def4 { get; set; }
        public string user_def5 { get; set; }
        public string user_def6 { get; set; }
        public Nullable<double> user_def7 { get; set; }
        public Nullable<double> user_def8 { get; set; }
        public Nullable<System.DateTime> user_def9 { get; set; }
        public Nullable<System.DateTime> user_def10 { get; set; }
        public Nullable<System.DateTime> insert_date { get; set; }
        public System.DateTime create_date { get; set; }
        public string create_by { get; set; }
        public string host_source { get; set; }
        public byte[] rowversion { get; set; }
        public Nullable<System.DateTime> delivery_date_plan { get; set; }
    }
}
