//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_NEW.Source
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_host_export_interface_sap_hana
    {
        public System.Guid interface_id { get; set; }
        public string unloading_point { get; set; }
        public string process_type { get; set; }
        public string processing_status { get; set; }
        public Nullable<System.DateTime> posting_date { get; set; }
        public Nullable<System.DateTime> document_date { get; set; }
        public string delivery_note { get; set; }
        public string bill_of_lading { get; set; }
        public string user_name { get; set; }
        public string document_header_text { get; set; }
        public string item_number { get; set; }
        public string plant { get; set; }
        public string storage_location { get; set; }
        public string batch { get; set; }
        public string supplier_batch { get; set; }
        public string movement_type { get; set; }
        public Nullable<double> entry_quantity { get; set; }
        public string entry_unit { get; set; }
        public string purchase_order_number { get; set; }
        public string purchase_order_item { get; set; }
        public string item_text { get; set; }
        public string good_recipient { get; set; }
        public string cost_center { get; set; }
        public string destination_item_number { get; set; }
        public string destination_plant { get; set; }
        public string destination_storage_location { get; set; }
        public string destination_batch { get; set; }
        public string movement_indicator { get; set; }
        public Nullable<int> reason_for_movement { get; set; }
        public Nullable<System.DateTime> expiry_date { get; set; }
        public Nullable<System.DateTime> production_date { get; set; }
        public string gl_account { get; set; }
        public Nullable<System.Guid> reference_no { get; set; }
        public Nullable<System.Guid> ref_export_id { get; set; }
        public System.Guid wh_master_id { get; set; }
        public string wh_id { get; set; }
        public Nullable<System.Guid> ref_interface_id { get; set; }
        public string create_by { get; set; }
        public System.DateTime create_date { get; set; }
        public byte[] rowversion { get; set; }
        public Nullable<System.DateTime> export_date { get; set; }
        public string export_file_name { get; set; }
        public string export_error_msg { get; set; }
        public string lpn { get; set; }
        public string tran_type { get; set; }
    }
}
