//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_NEW.Source
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_wms_inventory_status
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public t_wms_inventory_status()
        {
            this.t_wms_inventory = new HashSet<t_wms_inventory>();
        }
    
        public System.Guid inventory_status_id { get; set; }
        public string inv_status { get; set; }
        public string description { get; set; }
        public string allocatable { get; set; }
        public Nullable<int> sequence { get; set; }
        public string is_active { get; set; }
        public System.DateTime create_date { get; set; }
        public string create_by { get; set; }
        public byte[] rowversion { get; set; }
        public string lims_inv_status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_wms_inventory> t_wms_inventory { get; set; }
    }
}
