//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_NEW.Source
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_wms_inventory_bom
    {
        public int inventory_bom_id { get; set; }
        public System.Guid wh_master_id { get; set; }
        public System.Guid owner_id { get; set; }
        public string bom_id { get; set; }
        public System.Guid bom_wh_item_master_id { get; set; }
        public System.Guid bom_item_master_id { get; set; }
        public string bom_item_number { get; set; }
        public Nullable<double> quantity_receive { get; set; }
        public Nullable<double> quantity_ship { get; set; }
        public string create_by { get; set; }
        public System.DateTime create_date { get; set; }
        public byte[] rowversion { get; set; }
    }
}
