//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_NEW.Source
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_wms_shelf_life
    {
        public System.Guid shelf_life_id { get; set; }
        public System.Guid wh_master_id { get; set; }
        public System.Guid owner_id { get; set; }
        public System.Guid category_id { get; set; }
        public System.Guid item_master_id { get; set; }
        public System.Guid customer_id { get; set; }
        public string owner_code { get; set; }
        public string customer_name { get; set; }
        public Nullable<int> shelf_life_day_remaining { get; set; }
        public System.DateTime create_date { get; set; }
        public string create_by { get; set; }
        public byte[] rowversion { get; set; }
    
        public virtual t_wms_category t_wms_category { get; set; }
        public virtual t_wms_customer t_wms_customer { get; set; }
        public virtual t_wms_owner t_wms_owner { get; set; }
        public virtual t_wms_wh t_wms_wh { get; set; }
        public virtual t_wms_item t_wms_item { get; set; }
    }
}
