//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_NEW.Source
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_wms_outbound_group_bom
    {
        public System.Guid outbound_order_bom_id { get; set; }
        public System.Guid outbound_order_master_id { get; set; }
        public int bom_id { get; set; }
        public Nullable<System.Guid> wh_item_master_id { get; set; }
        public Nullable<System.Guid> item_master_id { get; set; }
        public string item_number { get; set; }
        public string bom_raw_code { get; set; }
        public double quantity { get; set; }
        public string create_by { get; set; }
        public System.DateTime create_date { get; set; }
        public string update_by { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public byte[] rowversion { get; set; }
    }
}
