//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_NEW.Source
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_wms_outbound_bom_detail
    {
        public System.Guid outbound_order_detail_id { get; set; }
        public System.Guid outbound_order_master_id { get; set; }
        public System.Guid wh_item_master_id { get; set; }
        public System.Guid item_master_id { get; set; }
        public string item_number { get; set; }
        public string line_number { get; set; }
        public double quantity_order { get; set; }
        public double quantity_ship { get; set; }
        public Nullable<double> quantity_pick { get; set; }
        public Nullable<double> quantity_load { get; set; }
        public System.Guid item_uom_id { get; set; }
        public string uom { get; set; }
        public string item_status { get; set; }
        public string lpn { get; set; }
        public string lot_number { get; set; }
        public string expiry_date { get; set; }
        public string serial_number { get; set; }
        public string attribute1 { get; set; }
        public string attribute2 { get; set; }
        public string attribute3 { get; set; }
        public string attribute4 { get; set; }
        public string attribute5 { get; set; }
        public string item_description { get; set; }
        public string customer_item_code { get; set; }
        public string dangerous_good_flag { get; set; }
        public Nullable<double> price { get; set; }
        public string grade { get; set; }
        public string default_item_status { get; set; }
        public string staging_item_status { get; set; }
        public string user_def1 { get; set; }
        public string user_def2 { get; set; }
        public string user_def3 { get; set; }
        public string user_def4 { get; set; }
        public string user_def5 { get; set; }
        public string user_def6 { get; set; }
        public Nullable<double> user_def7 { get; set; }
        public Nullable<double> user_def8 { get; set; }
        public Nullable<System.DateTime> user_def9 { get; set; }
        public Nullable<System.DateTime> user_def10 { get; set; }
        public string wh_item_fg { get; set; }
        public int bom_id { get; set; }
        public string create_by { get; set; }
        public System.DateTime create_date { get; set; }
        public string update_by { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public byte[] rowversion { get; set; }
    
        public virtual t_wms_outbound_bom_master t_wms_outbound_bom_master { get; set; }
        public virtual t_wms_wh_item t_wms_wh_item { get; set; }
    }
}
