//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_NEW.Source
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_wms_item_crossref
    {
        public System.Guid alternate_id { get; set; }
        public System.Guid item_master_id { get; set; }
        public string alternate_item_number { get; set; }
        public Nullable<System.Guid> item_uom_id { get; set; }
        public string is_active { get; set; }
        public string create_by { get; set; }
        public System.DateTime create_date { get; set; }
        public string update_by { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public byte[] rowversion { get; set; }
    
        public virtual t_wms_item t_wms_item { get; set; }
        public virtual t_wms_item_uom t_wms_item_uom { get; set; }
    }
}
