//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_NEW.Source
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_wms_count_temporary_external
    {
        public System.Guid running_id { get; set; }
        public System.Guid location_id { get; set; }
        public System.Guid wh_item_master_id { get; set; }
        public string inv_status { get; set; }
        public string parent_lpn { get; set; }
        public string lpn { get; set; }
        public string lot_number { get; set; }
        public string expiry_date { get; set; }
        public string serial_number { get; set; }
        public string attribute1 { get; set; }
        public string attribute2 { get; set; }
        public string attribute3 { get; set; }
        public string attribute4 { get; set; }
        public string attribute5 { get; set; }
        public Nullable<double> stock_qty { get; set; }
        public string create_by { get; set; }
        public System.DateTime create_date { get; set; }
        public byte[] rowversion { get; set; }
        public string lot { get; set; }
    }
}
