//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_NEW.Source
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_wms_truck_type
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public t_wms_truck_type()
        {
            this.t_wms_truck = new HashSet<t_wms_truck>();
        }
    
        public System.Guid truck_type_id { get; set; }
        public string truck_type { get; set; }
        public Nullable<int> wheel { get; set; }
        public double volume { get; set; }
        public double weight { get; set; }
        public double length { get; set; }
        public double width { get; set; }
        public double height { get; set; }
        public double factor { get; set; }
        public string is_active { get; set; }
        public string create_by { get; set; }
        public System.DateTime create_date { get; set; }
        public string update_by { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public byte[] rowversion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_wms_truck> t_wms_truck { get; set; }
    }
}
