//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_NEW.Source
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_wms_print_label
    {
        public System.Guid print_label_id { get; set; }
        public string wh_id { get; set; }
        public Nullable<System.Guid> inbound_order_master_id { get; set; }
        public string inbound_order_number { get; set; }
        public Nullable<System.Guid> inbound_order_detail_id { get; set; }
        public string line_number { get; set; }
        public Nullable<int> row_print { get; set; }
        public string lpn { get; set; }
        public Nullable<System.Guid> wh_item_master_id { get; set; }
        public string item_number { get; set; }
        public string item_description { get; set; }
        public Nullable<double> quantity_order { get; set; }
        public Nullable<System.Guid> item_uom_id { get; set; }
        public string uom { get; set; }
        public string lot_number { get; set; }
        public Nullable<System.DateTime> mfg_date { get; set; }
        public Nullable<System.DateTime> expiry_date { get; set; }
        public string attribute1 { get; set; }
        public string production_line { get; set; }
        public Nullable<double> pack_size_per_pallet { get; set; }
        public Nullable<System.Guid> pack_size_uom_id { get; set; }
        public string pack_size_uom { get; set; }
        public Nullable<double> pack_size_conversion_factor { get; set; }
        public Nullable<System.Guid> pallet_size_uom_id { get; set; }
        public string pallet_size_uom { get; set; }
        public Nullable<double> pallet_size_conversion_factor { get; set; }
        public string is_print { get; set; }
        public string is_received { get; set; }
        public Nullable<System.DateTime> print_date { get; set; }
        public string create_by { get; set; }
        public System.DateTime create_date { get; set; }
        public string update_by { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public byte[] rowversion { get; set; }
        public string ref_lpn { get; set; }
        public Nullable<int> pallet_seq { get; set; }
        public string is_cancelled { get; set; }
        public string is_interface_hana { get; set; }
    }
}
