//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_NEW.Source
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_wms_inbound_detail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public t_wms_inbound_detail()
        {
            this.t_wms_receipt_detail = new HashSet<t_wms_receipt_detail>();
        }
    
        public System.Guid inbound_order_detail_id { get; set; }
        public System.Guid inbound_order_master_id { get; set; }
        public System.Guid wh_item_master_id { get; set; }
        public System.Guid item_master_id { get; set; }
        public System.Guid item_uom_id { get; set; }
        public string item_number { get; set; }
        public string line_number { get; set; }
        public double quantity_order { get; set; }
        public double quantity_receive { get; set; }
        public string uom { get; set; }
        public string item_status { get; set; }
        public string lpn { get; set; }
        public string default_item_status { get; set; }
        public Nullable<double> price { get; set; }
        public string grade { get; set; }
        public string over_receipt_allowed { get; set; }
        public Nullable<double> over_receipt_percentage { get; set; }
        public string source_of_record { get; set; }
        public string lot_number { get; set; }
        public Nullable<System.DateTime> mfg_date { get; set; }
        public string expiry_date { get; set; }
        public string serial_number { get; set; }
        public string attribute1 { get; set; }
        public string attribute2 { get; set; }
        public string attribute3 { get; set; }
        public string attribute4 { get; set; }
        public string attribute5 { get; set; }
        public string ref_id { get; set; }
        public Nullable<System.DateTime> receive_date { get; set; }
        public Nullable<int> bom_detail_id { get; set; }
        public Nullable<int> bom_id { get; set; }
        public Nullable<System.Guid> inbound_order_bom_id { get; set; }
        public Nullable<System.Guid> bom_wh_item_master_id { get; set; }
        public Nullable<System.Guid> bom_item_master_id { get; set; }
        public string bom_item_number { get; set; }
        public Nullable<double> bom_detail_quantity { get; set; }
        public Nullable<double> bom_quantity_receive { get; set; }
        public string production_line { get; set; }
        public string ref_outbound_order_number { get; set; }
        public string ref_item_number { get; set; }
        public Nullable<int> order_sequence { get; set; }
        public Nullable<System.Guid> pack_size_uom_id { get; set; }
        public string pack_size_uom { get; set; }
        public Nullable<double> pack_size_conversion_factor { get; set; }
        public Nullable<System.Guid> pallet_size_uom_id { get; set; }
        public string pallet_size_uom { get; set; }
        public Nullable<double> pallet_size_conversion_factor { get; set; }
        public string ref_lpn { get; set; }
        public string user_def1 { get; set; }
        public string user_def2 { get; set; }
        public string user_def3 { get; set; }
        public string user_def4 { get; set; }
        public string user_def5 { get; set; }
        public string user_def6 { get; set; }
        public Nullable<double> user_def7 { get; set; }
        public Nullable<double> user_def8 { get; set; }
        public Nullable<System.DateTime> user_def9 { get; set; }
        public Nullable<System.DateTime> user_def10 { get; set; }
        public string create_by { get; set; }
        public System.DateTime create_date { get; set; }
        public string update_by { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public byte[] rowversion { get; set; }
    
        public virtual t_wms_wh_item t_wms_wh_item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_wms_receipt_detail> t_wms_receipt_detail { get; set; }
        public virtual t_wms_item_uom t_wms_item_uom { get; set; }
        public virtual t_wms_inbound_master t_wms_inbound_master { get; set; }
    }
}
