//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_NEW.Source
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_wms_count_external_close_plan
    {
        public System.Guid close_id { get; set; }
        public Nullable<System.Guid> count_master_id { get; set; }
        public string processing_status { get; set; }
        public System.DateTime create_date { get; set; }
        public string create_by { get; set; }
    }
}
