//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_NEW.Source
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_wms_replenishment_task
    {
        public System.Guid replenishment_task_id { get; set; }
        public System.Guid wh_master_id { get; set; }
        public string wh_id { get; set; }
        public System.Guid owner_id { get; set; }
        public string owner_code { get; set; }
        public System.Guid source_location_id { get; set; }
        public string source_location { get; set; }
        public System.Guid destination_location_id { get; set; }
        public string destination_location { get; set; }
        public string lpn { get; set; }
        public System.Guid wh_item_master_id { get; set; }
        public string item_number { get; set; }
        public string item_description { get; set; }
        public string lot_number { get; set; }
        public Nullable<System.DateTime> mfg_date { get; set; }
        public string expiry_date { get; set; }
        public string attribute1 { get; set; }
        public string attribute2 { get; set; }
        public string attribute3 { get; set; }
        public string attribute4 { get; set; }
        public string attribute5 { get; set; }
        public System.Guid inventory_status_id { get; set; }
        public string inventory_status { get; set; }
        public System.DateTime receive_date { get; set; }
        public string is_replenish { get; set; }
        public System.Guid inventory_id { get; set; }
        public System.Guid attribute_group_id { get; set; }
        public double quantity { get; set; }
        public string uom { get; set; }
        public Nullable<System.Guid> source_zone_id { get; set; }
        public string source_zone { get; set; }
        public Nullable<System.Guid> destination_zone_id { get; set; }
        public string destination_zone { get; set; }
        public Nullable<System.Guid> stg_location_id { get; set; }
        public string stg_location { get; set; }
        public string create_by { get; set; }
        public System.DateTime create_date { get; set; }
    }
}
