//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_NEW.Source
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_wms_inventory
    {
        public System.Guid inventory_id { get; set; }
        public System.Guid wh_master_id { get; set; }
        public System.Guid owner_id { get; set; }
        public System.Guid wh_item_master_id { get; set; }
        public System.Guid location_id { get; set; }
        public System.Guid inventory_status_id { get; set; }
        public string inv_type { get; set; }
        public System.Guid attribute_group_id { get; set; }
        public double quantity { get; set; }
        public double quantity_allocated { get; set; }
        public double quantity_incoming { get; set; }
        public string lpn { get; set; }
        public string parent_lpn { get; set; }
        public Nullable<double> volumn { get; set; }
        public Nullable<double> weight { get; set; }
        public System.DateTime receive_date { get; set; }
        public Nullable<System.DateTime> mfg_date { get; set; }
        public string user_def1 { get; set; }
        public string user_def2 { get; set; }
        public string user_def3 { get; set; }
        public string user_def4 { get; set; }
        public string user_def5 { get; set; }
        public string user_def6 { get; set; }
        public Nullable<double> user_def7 { get; set; }
        public Nullable<double> user_def8 { get; set; }
        public Nullable<System.DateTime> user_def9 { get; set; }
        public Nullable<System.DateTime> user_def10 { get; set; }
        public Nullable<double> volumn_by_lpn { get; set; }
        public Nullable<double> weight_by_lpn { get; set; }
        public string create_by { get; set; }
        public System.DateTime create_date { get; set; }
        public byte[] rowversion { get; set; }
    
        public virtual t_wms_owner t_wms_owner { get; set; }
        public virtual t_wms_wh t_wms_wh { get; set; }
        public virtual t_wms_wh_item t_wms_wh_item { get; set; }
        public virtual t_wms_inventory_status t_wms_inventory_status { get; set; }
        public virtual t_wms_location t_wms_location { get; set; }
    }
}
