//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_NEW.Source
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_wms_count_plan_master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public t_wms_count_plan_master()
        {
            this.t_wms_count_plan_detail = new HashSet<t_wms_count_plan_detail>();
            this.t_wms_count_reconcile = new HashSet<t_wms_count_reconcile>();
        }
    
        public System.Guid count_master_id { get; set; }
        public System.Guid wh_master_id { get; set; }
        public System.Guid owner_id { get; set; }
        public string count_id { get; set; }
        public string count_status { get; set; }
        public string priority { get; set; }
        public string description { get; set; }
        public string count_generate_method { get; set; }
        public string count_plan_type { get; set; }
        public System.DateTime create_date { get; set; }
        public string create_by { get; set; }
        public Nullable<System.DateTime> close_date { get; set; }
        public string close_by { get; set; }
        public string close_remark { get; set; }
        public byte[] rowversion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_wms_count_plan_detail> t_wms_count_plan_detail { get; set; }
        public virtual t_wms_owner t_wms_owner { get; set; }
        public virtual t_wms_wh t_wms_wh { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_wms_count_reconcile> t_wms_count_reconcile { get; set; }
    }
}
