//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_NEW.Source
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_host_wms_customer
    {
        public System.Guid customer_id { get; set; }
        public string host_record_id { get; set; }
        public string processing_status { get; set; }
        public string customer_code { get; set; }
        public string name { get; set; }
        public string phone { get; set; }
        public string fax { get; set; }
        public string email { get; set; }
        public string contact { get; set; }
        public string create_by { get; set; }
        public System.DateTime create_date { get; set; }
        public string interface_msg { get; set; }
    }
}
