//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_NEW.Source
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_outbound_viewer_sum_qty_by_item
    {
        public Nullable<System.Guid> wh_master_id { get; set; }
        public string wh_id { get; set; }
        public Nullable<System.Guid> owner_id { get; set; }
        public string owner_code { get; set; }
        public Nullable<System.DateTime> delivery_date_plan { get; set; }
        public System.Guid wh_item_master_id { get; set; }
        public Nullable<System.Guid> item_master_id { get; set; }
        public string item_number { get; set; }
        public string item_description { get; set; }
        public Nullable<System.Guid> category_id { get; set; }
        public string item_category { get; set; }
        public Nullable<System.Guid> item_uom_id { get; set; }
        public string uom { get; set; }
        public string uom_prompt { get; set; }
        public Nullable<double> quantity_order { get; set; }
    }
}
