//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_NEW.Source
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_tms_assign_order_detail
    {
        public Nullable<System.Guid> location_id { get; set; }
        public int is_checked { get; set; }
        public int is_allow_check { get; set; }
        public string door { get; set; }
        public string truck_type { get; set; }
        public string license { get; set; }
        public string head_tail { get; set; }
        public Nullable<System.DateTime> assgin_date { get; set; }
        public Nullable<System.Guid> wh_master_id { get; set; }
        public Nullable<System.Guid> outbound_order_master_id { get; set; }
        public Nullable<System.Guid> truck_manifest_id { get; set; }
    }
}
