//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_NEW.Source
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_tms_assign_order_uncheck
    {
        public Nullable<System.Guid> outbound_pick_detail_id { get; set; }
        public System.Guid outbound_pick_master_id { get; set; }
        public string outbound_order_number { get; set; }
        public System.Guid outbound_order_master_id { get; set; }
        public string lpn { get; set; }
        public Nullable<System.DateTime> check_date { get; set; }
        public Nullable<System.Guid> location_id { get; set; }
        public string door { get; set; }
        public string truck_type { get; set; }
        public string license { get; set; }
        public string head_tail { get; set; }
        public Nullable<System.DateTime> register_date { get; set; }
        public Nullable<System.Guid> truck_manifest_id { get; set; }
    }
}
