//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_NEW.Source
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_wms_count_reconcile_merge_summary
    {
        public System.Guid count_master_id { get; set; }
        public Nullable<double> total_stock_qty { get; set; }
        public Nullable<double> total_count_qty { get; set; }
        public Nullable<double> total_diff_qty { get; set; }
    }
}
