//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_NEW.Source
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_wms_dashboard_warehouse_virtual
    {
        public System.Guid wh_master_id { get; set; }
        public string wh_id { get; set; }
        public Nullable<int> x_max { get; set; }
        public Nullable<int> y_max { get; set; }
        public Nullable<System.Guid> zone_id { get; set; }
        public string zone { get; set; }
        public string zone_type { get; set; }
        public System.Guid location_id { get; set; }
        public string location { get; set; }
        public string loc_type { get; set; }
        public string location_level { get; set; }
        public Nullable<double> capacity_qty { get; set; }
        public Nullable<double> x_cordinate { get; set; }
        public Nullable<double> y_cordinate { get; set; }
        public Nullable<double> length { get; set; }
        public Nullable<double> width { get; set; }
        public Nullable<double> height { get; set; }
        public string lpn_controlled { get; set; }
        public string mix_owners { get; set; }
        public string mix_lot { get; set; }
        public string mix_expiry_dates { get; set; }
        public string mix_items { get; set; }
        public string mix_status { get; set; }
        public string mix_attribute1 { get; set; }
        public string mix_attribute2 { get; set; }
        public string mix_attribute3 { get; set; }
        public string mix_attribute4 { get; set; }
        public string mix_attribute5 { get; set; }
        public Nullable<double> current_qty { get; set; }
        public Nullable<double> available_qty { get; set; }
        public Nullable<double> usage_qty { get; set; }
    }
}
