//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_NEW.Source
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_wms_dashb_center_period_inbound
    {
        public System.Guid wh_master_id { get; set; }
        public string wh_id { get; set; }
        public System.DateTime trans_date { get; set; }
        public Nullable<double> quantity { get; set; }
    }
}
