//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_NEW.Source
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_wms_export_inbound_detail_receipt
    {
        public string sys_id { get; set; }
        public System.Guid wh_master_id { get; set; }
        public System.Guid owner_id { get; set; }
        public string owner_code { get; set; }
        public string inbound_order_number { get; set; }
        public string order_type { get; set; }
        public string order_status { get; set; }
        public string line_number { get; set; }
        public string item_number { get; set; }
        public string description { get; set; }
        public string lot_number { get; set; }
        public Nullable<System.DateTime> mfg_date { get; set; }
        public Nullable<System.DateTime> expiry_date { get; set; }
        public string serial_number { get; set; }
        public double quantity_received { get; set; }
        public string uom { get; set; }
        public string receipt_item_status { get; set; }
        public System.Guid category_id { get; set; }
        public string item_category { get; set; }
        public Nullable<System.DateTime> receive_date { get; set; }
        public string project_manager { get; set; }
        public string customer_by_line { get; set; }
        public string receipt_number { get; set; }
        public string receipt_no { get; set; }
        public string production_line { get; set; }
        public string attribute1 { get; set; }
        public Nullable<System.Guid> customer_id { get; set; }
        public string customer_code { get; set; }
        public string customer_name { get; set; }
        public string pack_size_uom { get; set; }
        public double alter_quantity_receive { get; set; }
        public string create_by { get; set; }
        public System.DateTime create_date { get; set; }
        public Nullable<System.DateTime> print_date { get; set; }
        public string lpn { get; set; }
        public string remark { get; set; }
    }
}
