//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_NEW.Source
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_wms_outbound_detail_linenumber
    {
        public System.Guid outbound_order_detail_id { get; set; }
        public System.Guid outbound_order_master_id { get; set; }
        public string line_number { get; set; }
        public Nullable<int> line_number_int { get; set; }
        public string default_item_status { get; set; }
        public string item_number { get; set; }
        public string item_description { get; set; }
        public string bom_master { get; set; }
        public Nullable<int> bom_detail_id { get; set; }
        public Nullable<int> bom_id { get; set; }
        public string item_category { get; set; }
        public string category_description { get; set; }
        public string lot_number { get; set; }
        public string lpn { get; set; }
        public string expiry_date { get; set; }
        public string grade { get; set; }
        public Nullable<double> price { get; set; }
        public double quantity_order { get; set; }
        public Nullable<double> quantity_pick { get; set; }
        public Nullable<double> quantity_load { get; set; }
        public double quantity_ship { get; set; }
        public string uom { get; set; }
        public string create_by { get; set; }
        public System.DateTime create_date { get; set; }
        public string attribute1 { get; set; }
        public string attribute2 { get; set; }
        public string attribute3 { get; set; }
        public string attribute4 { get; set; }
        public string attribute5 { get; set; }
    }
}
