//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_NEW.Source
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_wms_inventory_data_reprint
    {
        public System.Guid inventory_id { get; set; }
        public System.Guid attribute_group_id { get; set; }
        public string inv_type { get; set; }
        public string wh_id { get; set; }
        public System.Guid wh_master_id { get; set; }
        public System.Guid owner_id { get; set; }
        public string owner_code { get; set; }
        public Nullable<System.Guid> zone_id { get; set; }
        public string zone { get; set; }
        public System.Guid location_id { get; set; }
        public string location { get; set; }
        public string parent_lpn { get; set; }
        public string lpn { get; set; }
        public System.Guid category_id { get; set; }
        public string item_category { get; set; }
        public string cate_description { get; set; }
        public System.Guid wh_item_master_id { get; set; }
        public System.Guid item_master_id { get; set; }
        public string item_number { get; set; }
        public string description { get; set; }
        public System.Guid item_uom_id { get; set; }
        public string uom_prompt { get; set; }
        public string uom { get; set; }
        public double quantity { get; set; }
        public double quantity_allocated { get; set; }
        public string inv_status { get; set; }
        public System.Guid inventory_status_id { get; set; }
        public System.DateTime receive_date { get; set; }
        public string receive_date_filter { get; set; }
        public string lot_number { get; set; }
        public Nullable<System.DateTime> mfg_date { get; set; }
        public string expiry_date { get; set; }
        public Nullable<System.DateTime> exp_date { get; set; }
        public string attribute1 { get; set; }
        public string qr_format { get; set; }
    }
}
