//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_NEW.Source
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_wms_receipt_detail_v2
    {
        public System.Guid receipt_detail_id { get; set; }
        public System.Guid receipt_header_id { get; set; }
        public Nullable<System.Guid> inbound_order_master_id { get; set; }
        public string inbound_order_number { get; set; }
        public System.Guid inbound_order_detail_id { get; set; }
        public Nullable<System.Guid> wh_item_master_id { get; set; }
        public double quantity_received { get; set; }
        public System.Guid item_uom_id { get; set; }
        public string receipt_item_status { get; set; }
        public string location_received { get; set; }
        public string lpn { get; set; }
        public string parent_lpn { get; set; }
        public string lot_number { get; set; }
        public Nullable<System.DateTime> expiry_date { get; set; }
        public string serial_number { get; set; }
        public string attribute1 { get; set; }
        public string attribute2 { get; set; }
        public string attribute3 { get; set; }
        public string attribute4 { get; set; }
        public string attribute5 { get; set; }
        public Nullable<System.DateTime> posting_date { get; set; }
        public System.DateTime create_date { get; set; }
        public string create_by { get; set; }
        public string line_number { get; set; }
        public double quantity_order { get; set; }
        public string over_receipt_allowed { get; set; }
        public Nullable<System.Guid> item_master_id { get; set; }
        public string item_number { get; set; }
        public string item_description { get; set; }
        public string uom { get; set; }
        public Nullable<System.Guid> category_id { get; set; }
        public string item_category { get; set; }
        public string category_description { get; set; }
        public Nullable<int> pallet_seq { get; set; }
    }
}
