//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_NEW.Source
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_wms_mapping_location_item
    {
        public string key_id { get; set; }
        public System.Guid item_master_id { get; set; }
        public string item_number { get; set; }
        public string description { get; set; }
        public string location { get; set; }
        public System.Guid location_id { get; set; }
        public Nullable<bool> is_active { get; set; }
        public string create_by { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
    }
}
