//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_NEW.Source
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_wms_print_lpn
    {
        public string item_number { get; set; }
        public string description { get; set; }
        public Nullable<double> cost { get; set; }
        public Nullable<double> price { get; set; }
        public string inventory_type { get; set; }
        public string model { get; set; }
        public string style { get; set; }
        public string color { get; set; }
        public string size { get; set; }
        public string coo { get; set; }
        public string grade { get; set; }
        public string user_def1 { get; set; }
        public string user_def2 { get; set; }
        public string user_def3 { get; set; }
        public string user_def4 { get; set; }
        public string user_def5 { get; set; }
        public string user_def6 { get; set; }
        public Nullable<double> user_def7 { get; set; }
        public Nullable<double> user_def8 { get; set; }
        public Nullable<System.DateTime> user_def9 { get; set; }
        public Nullable<System.DateTime> user_def10 { get; set; }
        public string uom { get; set; }
        public double conversion_factor { get; set; }
        public string uom_prompt { get; set; }
        public string gtin { get; set; }
        public Nullable<double> length { get; set; }
        public Nullable<double> width { get; set; }
        public Nullable<double> height { get; set; }
        public Nullable<double> weight { get; set; }
        public Nullable<double> gross_weight { get; set; }
        public Nullable<double> tare_weight { get; set; }
        public string line_number { get; set; }
        public double quantity_order { get; set; }
        public double quantity_receive { get; set; }
        public string item_status { get; set; }
        public string lpn { get; set; }
        public string default_item_status { get; set; }
        public Nullable<double> detail_price { get; set; }
        public string detail_grade { get; set; }
        public string lot_number { get; set; }
        public string expiry_date { get; set; }
        public string serial_number { get; set; }
        public string detail_udf1 { get; set; }
        public string detail_udf2 { get; set; }
        public string detail_udf3 { get; set; }
        public string detail_udf4 { get; set; }
        public string detail_udf5 { get; set; }
        public string detail_udf6 { get; set; }
        public Nullable<double> detail_udf7 { get; set; }
        public Nullable<double> detail_udf8 { get; set; }
        public Nullable<System.DateTime> detail_udf9 { get; set; }
        public Nullable<System.DateTime> detail_udf10 { get; set; }
        public string inbound_order_number { get; set; }
        public string order_type { get; set; }
        public string order_status { get; set; }
        public string master_desc { get; set; }
        public Nullable<System.DateTime> expected_delivery_date { get; set; }
        public string reference_number { get; set; }
        public string master_udf1 { get; set; }
        public string master_udf2 { get; set; }
        public string master_udf3 { get; set; }
        public string master_udf4 { get; set; }
        public string master_udf5 { get; set; }
        public string master_udf6 { get; set; }
        public Nullable<double> master_udf7 { get; set; }
        public Nullable<double> master_udf8 { get; set; }
        public Nullable<System.DateTime> master_udf9 { get; set; }
        public Nullable<System.DateTime> master_udf10 { get; set; }
        public Nullable<System.DateTime> close_date { get; set; }
        public string close_remark { get; set; }
        public string copy_no { get; set; }
        public string wh_id { get; set; }
        public string wh_name { get; set; }
        public string wh_desc { get; set; }
        public string owner_code { get; set; }
        public string owner_name { get; set; }
        public string own_desc { get; set; }
        public System.Guid inbound_order_detail_id { get; set; }
        public System.Guid inbound_order_master_id { get; set; }
        public string dg_code { get; set; }
        public string attribute1 { get; set; }
        public string attribute2 { get; set; }
        public string attribute3 { get; set; }
        public string attribute4 { get; set; }
        public string attribute5 { get; set; }
        public System.Guid wh_item_master_id { get; set; }
        public System.Guid item_uom_id { get; set; }
        public string RunningLPN { get; set; }
        public string RunningSerial { get; set; }
        public string RunningSerial_INT { get; set; }
    }
}
