//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_NEW.Source
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_wms_inbound_master_viewer
    {
        public System.Guid inbound_order_master_id { get; set; }
        public System.Guid wh_master_id { get; set; }
        public string wh_id { get; set; }
        public System.Guid owner_id { get; set; }
        public string owner_code { get; set; }
        public Nullable<System.Guid> supplier_id { get; set; }
        public Nullable<System.Guid> customer_id { get; set; }
        public string inbound_order_number { get; set; }
        public string ref_inbound_order_number { get; set; }
        public string ref_outbound_order_number { get; set; }
        public string order_type { get; set; }
        public string order_status { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> expected_delivery_date { get; set; }
        public string create_by { get; set; }
        public System.DateTime create_date { get; set; }
        public string make_to { get; set; }
        public string supplier_code { get; set; }
        public string supplier_name { get; set; }
        public string customer_code { get; set; }
        public string customer_name { get; set; }
        public Nullable<int> count_detail { get; set; }
        public Nullable<double> quantity_order { get; set; }
        public Nullable<double> pack_size_per_pallet { get; set; }
        public string add_production { get; set; }
        public string production_line { get; set; }
        public string item_number { get; set; }
    }
}
