//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_NEW.Source
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_wms_inventory_data_for_dashboard_exp
    {
        public System.Guid inventory_id { get; set; }
        public System.Guid attribute_group_id { get; set; }
        public System.Guid wh_master_id { get; set; }
        public System.Guid owner_id { get; set; }
        public System.Guid location_id { get; set; }
        public string parent_lpn { get; set; }
        public string lpn { get; set; }
        public System.Guid wh_item_master_id { get; set; }
        public double quantity { get; set; }
        public double quantity_allocated { get; set; }
        public double quantity_incoming { get; set; }
        public string inv_status { get; set; }
        public System.Guid inventory_status_id { get; set; }
        public string expiry_date { get; set; }
        public Nullable<System.DateTime> exp_date { get; set; }
    }
}
