//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_NEW.Source
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_wms_count_reconcile
    {
        public System.Guid wh_master_id { get; set; }
        public string wh_id { get; set; }
        public System.Guid count_reconcile_id { get; set; }
        public string count_id { get; set; }
        public string item_number { get; set; }
        public string description { get; set; }
        public string zone { get; set; }
        public string location { get; set; }
        public double stock_qty { get; set; }
        public double count_qty { get; set; }
        public double diff_qty { get; set; }
        public string uom_prompt { get; set; }
        public string create_by { get; set; }
        public System.DateTime create_date { get; set; }
        public string lpn { get; set; }
        public string lot { get; set; }
        public Nullable<System.DateTime> expiry_date { get; set; }
        public string serial_number { get; set; }
        public System.Guid count_master_id { get; set; }
        public string inv_status { get; set; }
        public string dg_code { get; set; }
        public Nullable<double> price { get; set; }
        public string grade { get; set; }
        public string approve_adjust { get; set; }
        public Nullable<double> cost { get; set; }
        public string adjust_status { get; set; }
        public System.Guid wh_item_master_id { get; set; }
        public string item_category { get; set; }
        public System.Guid category_id { get; set; }
        public string cate_description { get; set; }
        public string count_status { get; set; }
        public string count_plan_type { get; set; }
        public string create_plan_by { get; set; }
        public Nullable<double> host_qty { get; set; }
        public string parent_lpn { get; set; }
        public string owner_id { get; set; }
        public string attribute1 { get; set; }
        public string attribute2 { get; set; }
        public string attribute3 { get; set; }
        public string attribute4 { get; set; }
        public string attribute5 { get; set; }
    }
}
