//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_NEW.Source
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_wms_outbound_pick_detail_mini
    {
        public System.Guid outbound_order_master_id { get; set; }
        public string outbound_order_number { get; set; }
        public string load_id { get; set; }
        public System.Guid wh_master_id { get; set; }
        public System.Guid owner_id { get; set; }
        public string order_type { get; set; }
        public string order_status { get; set; }
        public Nullable<System.Guid> customer_id { get; set; }
        public string customer_code { get; set; }
        public Nullable<System.DateTime> ship_date_plan { get; set; }
        public System.Guid outbound_order_detail_id { get; set; }
        public System.Guid outbound_pick_master_id { get; set; }
        public Nullable<System.Guid> outbound_pick_detail_id { get; set; }
        public string line_number { get; set; }
        public Nullable<System.Guid> wh_item_master_id { get; set; }
        public System.Guid item_master_id { get; set; }
        public string item_number { get; set; }
        public string description { get; set; }
        public string default_item_status { get; set; }
        public string sn_control { get; set; }
        public string lot_control { get; set; }
        public string expiry_date_control { get; set; }
        public string attribute1_control { get; set; }
        public string attribute2_control { get; set; }
        public string attribute3_control { get; set; }
        public string attribute4_control { get; set; }
        public string attribute5_control { get; set; }
        public System.Guid item_uom_id { get; set; }
        public string uom { get; set; }
        public string uom_prompt { get; set; }
        public double conversion_factor { get; set; }
        public string parent_lpn { get; set; }
        public string lpn { get; set; }
        public string lot_number { get; set; }
        public string expiry_date { get; set; }
        public string attribute1 { get; set; }
        public string attribute2 { get; set; }
        public string attribute3 { get; set; }
        public string attribute4 { get; set; }
        public string attribute5 { get; set; }
        public double quantity_order { get; set; }
        public Nullable<double> quantity_plan { get; set; }
        public double quantity_pick { get; set; }
        public double sn_quantity { get; set; }
        public double quantity_stage { get; set; }
        public double quantity_load { get; set; }
        public double quantity_ship { get; set; }
        public Nullable<System.Guid> location_id { get; set; }
        public string location { get; set; }
        public string pick_location { get; set; }
        public string is_override { get; set; }
        public string serial_number { get; set; }
        public string pick_to_lpn { get; set; }
        public string pick_to_parent_lpn { get; set; }
        public Nullable<System.DateTime> receive_date { get; set; }
        public Nullable<System.DateTime> start_date_time { get; set; }
        public Nullable<System.DateTime> end_date_time { get; set; }
        public string pick_line_number { get; set; }
        public string load_status { get; set; }
        public Nullable<System.Guid> dock_door_id { get; set; }
        public string dock_door_lpn { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<System.Guid> staging_location_id { get; set; }
        public string staging_parent_lpn { get; set; }
        public string staging_lpn { get; set; }
    }
}
