//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_NEW.Source
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_wms_count_plan_detail
    {
        public string wh_id { get; set; }
        public string count_id { get; set; }
        public string count_plan_type { get; set; }
        public string zone { get; set; }
        public string location { get; set; }
        public string item_number { get; set; }
        public System.Guid count_plan_detail_id { get; set; }
        public System.Guid count_master_id { get; set; }
        public string lpn_controlled { get; set; }
        public string expiry_date_control { get; set; }
        public string sn_control { get; set; }
        public string lot_control { get; set; }
        public System.Guid location_id { get; set; }
        public Nullable<System.Guid> wh_item_master_id { get; set; }
        public Nullable<System.Guid> item_master_id { get; set; }
        public string description { get; set; }
        public string dg_code { get; set; }
        public string brand_name { get; set; }
        public string inv_status { get; set; }
        public string grade { get; set; }
        public Nullable<double> price { get; set; }
        public string lpn { get; set; }
        public string create_by { get; set; }
        public string parent_lpn { get; set; }
        public string item_category { get; set; }
        public Nullable<double> stock_qty { get; set; }
        public string uom_prompt { get; set; }
        public string owner_code { get; set; }
        public string lot { get; set; }
        public string expiry_date { get; set; }
        public string serial_number { get; set; }
        public string attribute1 { get; set; }
        public string attribute2 { get; set; }
        public string attribute3 { get; set; }
        public string attribute4 { get; set; }
        public string attribute5 { get; set; }
        public System.DateTime create_date { get; set; }
        public Nullable<System.Guid> category_id { get; set; }
        public string cate_description { get; set; }
    }
}
