//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecurityM.Source
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_com_menu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public t_com_menu()
        {
            this.t_com_user_group_menu = new HashSet<t_com_user_group_menu>();
        }
    
        public string menu_id { get; set; }
        public string app_id { get; set; }
        public string platform { get; set; }
        public string menu_group { get; set; }
        public Nullable<int> menu_group_sequence { get; set; }
        public string parent_menu_id { get; set; }
        public string menu_name { get; set; }
        public int menu_sequence { get; set; }
        public string process { get; set; }
        public string resource_master_id { get; set; }
        public string is_active { get; set; }
        public System.DateTime create_date { get; set; }
        public string create_by { get; set; }
        public byte[] rowversion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_com_user_group_menu> t_com_user_group_menu { get; set; }
    }
}
