//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecurityM.Source
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_com_application
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public t_com_application()
        {
            this.t_com_user_application = new HashSet<t_com_user_application>();
            this.t_com_config = new HashSet<t_com_config>();
            this.t_com_user_group = new HashSet<t_com_user_group>();
            this.t_com_user_logon = new HashSet<t_com_user_logon>();
            this.t_com_user_device = new HashSet<t_com_user_device>();
        }
    
        public string app_id { get; set; }
        public string application_name { get; set; }
        public string description { get; set; }
        public string license_type { get; set; }
        public string number_of_users { get; set; }
        public string is_active { get; set; }
        public string app_version { get; set; }
        public string date_installed { get; set; }
        public string expiry_date { get; set; }
        public string maintenance_support_date { get; set; }
        public string db_server_name { get; set; }
        public string db_name { get; set; }
        public string db_user { get; set; }
        public string db_password { get; set; }
        public string db_connectionstring { get; set; }
        public string environment { get; set; }
        public string security_mode { get; set; }
        public System.DateTime create_date { get; set; }
        public string create_by { get; set; }
        public byte[] rowversion { get; set; }
        public string use_expirydate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_com_user_application> t_com_user_application { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_com_config> t_com_config { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_com_user_group> t_com_user_group { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_com_user_logon> t_com_user_logon { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_com_user_device> t_com_user_device { get; set; }
    }
}
