//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecurityM.Source
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_com_locale
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public t_com_locale()
        {
            this.t_com_user = new HashSet<t_com_user>();
        }
    
        public string locale_id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string locale { get; set; }
        public string is_active { get; set; }
        public System.DateTime create_date { get; set; }
        public string create_by { get; set; }
        public byte[] rowversion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_com_user> t_com_user { get; set; }
    }
}
