//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_NEW.Transaction.Inbound.AscxControl
{


    public partial class ucInboundCancelPalletDetail
    {

        /// <summary>
        /// GridExt1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::_UControls.GridViewExt GridExt1;

        /// <summary>
        /// gridInboundOrderMasterId control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::_UControls.InputHidden gridInboundOrderMasterId;

        /// <summary>
        /// gcPrint control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::_UControls.GridColumnExt gcPrint;

        /// <summary>
        /// iColProductionLine control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::_UControls.GridColumnExt iColProductionLine;

        /// <summary>
        /// iColLPN control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::_UControls.GridColumnExt iColLPN;

        /// <summary>
        /// iColIsPrint control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::_UControls.GridColumnExt iColIsPrint;

        /// <summary>
        /// iColItemNumber control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::_UControls.GridColumnExt iColItemNumber;

        /// <summary>
        /// iColIsCancel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::_UControls.GridColumnExt iColIsCancel;
    }
}
