//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_NEW.Transaction.Inbound.AscxControl
{


    public partial class ucReceivePartial
    {

        /// <summary>
        /// updateCloseReceipt control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdatePanel updateCloseReceipt;

        /// <summary>
        /// ddlReceiptNo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::_UControls.InputDropDown ddlReceiptNo;

        /// <summary>
        /// txtStatus control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::_UControls.InputTextBox txtStatus;

        /// <summary>
        /// btnCloseReceipt control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::_UControls.ButtonExt btnCloseReceipt;

        /// <summary>
        /// btnSaveReceipt control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::_UControls.ButtonExt btnSaveReceipt;

        /// <summary>
        /// txtCreateBy control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::_UControls.InputTextBox txtCreateBy;

        /// <summary>
        /// txtCreateDate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::_UControls.InputTextDate txtCreateDate;

        /// <summary>
        /// txtCloseBy control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::_UControls.InputTextBox txtCloseBy;

        /// <summary>
        /// txtCloseDate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::_UControls.InputTextDate txtCloseDate;

        /// <summary>
        /// popupCloseReceipt control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::_UControls.PanelPopup popupCloseReceipt;

        /// <summary>
        /// lblValidateCloseOrder control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblValidateCloseOrder;

        /// <summary>
        /// btComfirm control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::_UControls.ButtonExt btComfirm;

        /// <summary>
        /// PanelTab1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::_UControls.PanelTab PanelTab1;

        /// <summary>
        /// PanelControlTab1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::_UControls.PanelCustom.PanelControlTab PanelControlTab1;

        /// <summary>
        /// GridExtSummary control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::_UControls.GridViewExt GridExtSummary;

        /// <summary>
        /// btRefreshDetailSummary control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::_UControls.ButtonExt btRefreshDetailSummary;

        /// <summary>
        /// hdfreceipt_header_id_summary control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::_UControls.InputHidden hdfreceipt_header_id_summary;

        /// <summary>
        /// GridColumnExt10 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::_UControls.GridColumnExt GridColumnExt10;

        /// <summary>
        /// GridColumnExt13 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::_UControls.GridColumnExt GridColumnExt13;

        /// <summary>
        /// GridColumnExt12 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::_UControls.GridColumnExt GridColumnExt12;

        /// <summary>
        /// GridColumnExt11 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::_UControls.GridColumnExt GridColumnExt11;

        /// <summary>
        /// GridColumnExt16 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::_UControls.GridColumnExt GridColumnExt16;

        /// <summary>
        /// GridColumnExt17 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::_UControls.GridColumnExt GridColumnExt17;

        /// <summary>
        /// GridColumnExt18 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::_UControls.GridColumnExt GridColumnExt18;

        /// <summary>
        /// PanelControlTab2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::_UControls.PanelCustom.PanelControlTab PanelControlTab2;

        /// <summary>
        /// GridExtDetail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::_UControls.GridViewExt GridExtDetail;

        /// <summary>
        /// btRefreshDetail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::_UControls.ButtonExt btRefreshDetail;

        /// <summary>
        /// hdfreceipt_header_id control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::_UControls.InputHidden hdfreceipt_header_id;

        /// <summary>
        /// GridColumnExt1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::_UControls.GridColumnExt GridColumnExt1;

        /// <summary>
        /// GridColumnExt4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::_UControls.GridColumnExt GridColumnExt4;

        /// <summary>
        /// GridColumnExt3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::_UControls.GridColumnExt GridColumnExt3;

        /// <summary>
        /// GridColumnExt2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::_UControls.GridColumnExt GridColumnExt2;

        /// <summary>
        /// GridColumnExt7 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::_UControls.GridColumnExt GridColumnExt7;

        /// <summary>
        /// GridColumnExt8 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::_UControls.GridColumnExt GridColumnExt8;

        /// <summary>
        /// GridColumnExt9 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::_UControls.GridColumnExt GridColumnExt9;

        /// <summary>
        /// PanelControlTab3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::_UControls.PanelCustom.PanelControlTab PanelControlTab3;

        /// <summary>
        /// txtUDF1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::_UControls.InputTextBox txtUDF1;

        /// <summary>
        /// txtUDF2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::_UControls.InputTextBox txtUDF2;

        /// <summary>
        /// txtUDF3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::_UControls.InputTextBox txtUDF3;

        /// <summary>
        /// txtUDF4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::_UControls.InputTextBox txtUDF4;

        /// <summary>
        /// txtUDF5 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::_UControls.InputTextBox txtUDF5;

        /// <summary>
        /// txtUDF6 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::_UControls.InputTextBox txtUDF6;

        /// <summary>
        /// txtUDF7 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::_UControls.InputTextNumber txtUDF7;

        /// <summary>
        /// txtUDF8 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::_UControls.InputTextNumber txtUDF8;

        /// <summary>
        /// txtUDF9 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::_UControls.InputTextDate txtUDF9;

        /// <summary>
        /// txtUDF10 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::_UControls.InputTextDate txtUDF10;

        /// <summary>
        /// PanelControlRow2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::_UControls.PanelCustom.PanelControlRow PanelControlRow2;
    }
}
