//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_NEW.Transaction.Inbound.AscxControl {
    
    
    public partial class ucReceiptDetail {
        
        /// <summary>
        /// GridExt1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::_UControls.GridViewExt GridExt1;
        
        /// <summary>
        /// btRefresh control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::_UControls.ButtonExt btRefresh;
        
        /// <summary>
        /// hdf_inbound_order_master_id control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::_UControls.InputHidden hdf_inbound_order_master_id;
    }
}
